// readable recipe names
export const readableRecipesLib = {
    "ATAC": "ATAC Sequencing",
    "Capture_ACCESS": "MSK-ACCESS",
    "Capture_CMO-CH": "CMO-CH",
    "Capture_Custom": "Custom Capture",
    "Capture_IMPACT": "IMPACT",
    "Capture_IMPACT-Heme": "IMPACT-Heme",
    "Capture_IMPACT-Mouse": "Mouse IMPACT",
    "Capture_Methyl": "Methyl Capture",
    "ddPCR": "ddPCR",
    "DNA_Amplicon": "Amplicon Sequencing",
    "DNA_ChIP": "ChIP Sequencing",
    "DNA_CRISPR": "CRISPR Sequencing",
    "DNA_Cut&Run": "CUT&RUN Sequencing",
    "DNA_SingleCellCNV": "Single Cell CNV Sequencing",
    "Extraction_Dual": "Dual DNA/RNA Extraction",
    "Extraction_Pickup": "DNA or RNA Extraction",
    "FA_CLA": "Cell Line Authentication",
    "FA_Custom": "Custom Fragment Analysis",
    "FA_Fingerprint": "Tumor/Normal Fingerprinting",
    "Nanopore_cDNA": "Nanopore cDNA Sequencing",
    "Nanopore_Chromium": "Nanopore 10X cDNA Sequencing",
    "Nanopore_Long-DNA": "Nanopore Long Read DNA Sequencing",
    "Nanopore_RNA":	"Nanopore Direct RNA Sequencing",
    "Nanopore_Short-DNA": "Nanopore Short Read DNA Sequencing",
    "PEDPEG": "PED-PEG",
    "QC_DNA": "DNA QC",
    "QC_Library": "Library QC",
    "QC_RNA": "RNA QC",
    "RNA_Capture": "RNA Capture",
    "RNA_PolyA": "RNA Seq - PolyA",
    "RNA_Ribodeplete": "RNA Seq - Ribodepletion",
    "RNA_SMARTer-Cells": "SMARTer from Cells",
    "RNA_SMARTer-RNA": "RNA Seq - SMARTer",
    "SC_Chromium-ATAC":	"10X scATAC Sequencing",
    "SC_Chromium-BCR": "10X scVDJ (BCR) Sequencing",
    "SC_Chromium-FB-3": "10X Feature Barcode/Hashtag Sequencing",
    "SC_Chromium-FB-5":	"10X Feature Barcode/Hashtag Sequencing",
    "SC_Chromium-GEX-3": "10X scRNA-Seq",
    "SC_Chromium-GEX-5": "10X scRNA-Seq",
    "SC_Chromium-Multiome":	"10X Multiome",
    "SC_Chromium-TCR": "10X scVDJ (TCR) Sequencing",
    "SC_DLP": "DLP+",
    "SC_SmartSeq": "SmartSeq v3 (384-well)",
    "Spatial_CosMx": "CosMx",
    "Spatial_GeoMx": "GeoMx",
    "Spatial_Visium": "Visium",
    "Spatial_Xenium": "Xenium",
    "TCR_IGO": "TCR Sequencing",
    "User_Amplicon": "Amplicon Sequencing",
    "User_ATAC": "ATAC Sequencing",
    "User_ChIP": "ChIP Sequencing",
    "User_Chromium": "10X GEX, VDJ, Feature Barcoding, or Cell Hashing",
    "User_Chromium-ATAC": "10X scATAC Sequencing",
    "User_Methyl": "Methylation Sequencing",
    "User_MissionBio": "MissionBio",
    "User_RNA":	"RNA Sequencing",
    "User_shRNA": "shRNA Sequencing",
    "User_SingleCellCNV": "Single Cell CNV Sequencing",
    "User_WGS":	"Whole Genome Sequencing",
    "WES_Human": "Whole Exome Sequencing",
    "WES_Mouse": "Mouse Whole Exome Sequencing",
    "WGS_Deep":	"Whole Genome Sequencing (deep or PCR-free)",
    "WGS_Metagenomic": "Metagenomic Sequencing",
    "WGS_Shallow": "Shallow Whole Genome Sequencing",
    "User_Archer": "Archer",
    "User_AmpliSeq": "AmpliSeq"
};