const validationPatterns = {
  userId: '^[A-Za-z0-9](?!.*__)[A-Za-z0-9\\,_-]{2}[A-Za-z0-9\\,_-]*$',
  patientId: '^[A-Za-z0-9][A-Za-z0-9\\,_-]*$',
  blockslidetube: '^.{1,25}$',
  number: '^[0-9.]*$',
  collectionYear: 'd{4}|^$',
  wellPosition: '[A-Za-z]+[0-9]+|^$',
  micronicTubeBarcode: '^[0-9]{10}$',
  alphanum: '[0-9a-zA-Z]',
  alphanumFour: '[0-9a-zA-Z]{4,}',
  alphanumdash: '^[A-Za-z0-9](?!.*__)[A-Za-z0-9\\,_-]{2}[A-Za-z0-9\\,_-]*$',
  cmoId: '^C[-|_].{6}$',
  dmpSampleId: '^P-[0-9]{7}-.{3}-.{3}$',
  dmpPatientId: '^P-[0-9]{7}$',
  mrn: '^[0-9]{8}$',
  groupingId: '[A-Za-z0-9\\,_-]{4,}',
  plateId: '^MSK-[A-Za-z0-9\\,_-]{10,}$',
};

export const gridColumns = {
  'Tracking ID': {
    name: 'Tracking ID',
    columnHeader: 'Tracking ID',
    data: 'trackingId',
  },
  'DMP Sample ID': {
    name: 'DMP Sample ID',
    columnHeader: 'DMP Sample ID',
    data: 'dmpSampleId',
  },
  'Investigator Patient ID (Study Subject Identifier)': {
    name: 'Investigator Patient ID (Study Subject Identifier)',
    columnHeader: 'Investigator Patient ID (Study Subject Identifier)',
    data: 'studySubjectIdentifier',
  },
  'Investigator Sample ID (Study Sample Identifier)': {
    name: 'Investigator Sample ID (Study Sample Identifier)',
    pattern: validationPatterns.dmpSampleId,
    columnHeader: 'Investigator Sample ID (Study Sample Identifier)',
    data: 'studySampleIdentifier',
  },
  'Sample Type': {
    name: 'Sample Type',
    columnHeader: 'Sample Type',
    data: 'sampleType',
    type: 'autocomplete',
    strict: true,
    error: 'Only dropdown options are permitted as values',
    picklistName: 'DmpSampleTypes',
  },
  'Specimen Type': {
    name: 'Specimen Type',
    columnHeader: 'Specimen Type',
    data: 'specimenType',
    type: 'autocomplete',
    strict: true,
    error: 'Only dropdown options are permitted as values',
    picklistName: 'DmpSpecimenTypes',
  },
  'Project PI': {
    name: 'Project PI',
    columnHeader: 'Project PI',
    data: 'projectPi',
  },
  'Project Title': {
    name: 'Project Title',
    columnHeader: 'Project Title',
    data: 'projectTitle',
  },
  'DMP to Transfer': {
    name: 'DMP to Transfer',
    columnHeader: 'DMP to Transfer',
    data: 'dmpToTransfer',
    source: ['yes', 'no'],
    type: 'autocomplete',
    strict: true,
    error: 'Only dropdown options are permitted as values',
  },
  'Molecular Pathology Accession Number': {
    name: 'Molecular Pathology Accession Number',
    columnHeader: 'Molecular Pathology Accession Number',
    data: 'molecularPathologyAccessionNumber',
  },

  'Sample Approved by CMO': {
    name: 'Sample Approved by CMO',
    columnHeader: 'Sample Approved by CMO',
    data: 'Sample Approved by CMO',
    type: 'autocomplete',
    strict: true,
    error: 'Only dropdown options are permitted as values',
    picklistName: 'DmpCmoSampleApproval',
  },
  'Variant Allele Frequency': {
    name: 'Variant Allele Frequency',
    columnHeader: 'Variant Allele Frequency',
    data: 'Variant Allele Frequency',
  },
  Coverage: {
    name: 'Coverage',
    columnHeader: 'Coverage',
    data: 'Coverage',
    type: 'autocomplete',
    strict: true,
    error: 'Only dropdown options are permitted as values',
    picklistName: 'DmpCoverage',
  },
  'Investigator Patient ID (Investigator Provided Study Subject Identifier)': {
    name:
      'Investigator Patient ID (Investigator Provided Study Subject Identifier)',
    columnHeader:
      'Investigator Patient ID (Investigator Provided Study Subject Identifier)',
    data: 'investigatorProvidedStudySubjectIdentifier',
  },
  'Investigator Sample ID (Investigator Provided Study Sample Identifier)': {
    name:
      'Investigator Sample ID (Investigator Provided Study Sample Identifier)',
    columnHeader:
      'Investigator Sample ID (Investigator Provided Study Sample Identifier)',
    data: 'investigatorProvidedStudySampleIdentifier',
    pattern: validationPatterns.dmpSampleId,
  },
  'Additional Info': {
    name: 'Additional Info',
    columnHeader: 'Additional Info',
    data: 'additionalInfo',
  },
};

export const dmpIntakeForms = {
  'DNA+CustomCapture': [
    ['Tracking ID', 'Required'],
    ['DMP Sample ID', 'Required'],
    ['Investigator Patient ID (Study Subject Identifier)', 'Required'],
    ['Investigator Sample ID (Study Sample Identifier)', 'Required'],
    ['Sample Type', 'Required'],
    ['Specimen Type', 'Required'],
    ['Project PI', 'Required'],
    ['Project Title', 'Required'],
    ['DMP to Transfer', 'Required'],
    ['Molecular Pathology Accession Number', 'Optional'],
  ],
  'DNA+QC_Pickup': [
    ['Tracking ID', 'Required'],
    ['DMP Sample ID', 'Required'],
    ['Investigator Patient ID (Study Subject Identifier)', 'Required'],
    ['Investigator Sample ID (Study Sample Identifier)', 'Required'],
    ['Sample Type', 'Required'],
    ['Specimen Type', 'Required'],
    ['Project PI', 'Required'],
    ['Project Title', 'Required'],
    ['DMP to Transfer', 'Required'],
    ['Molecular Pathology Accession Number', 'Optional'],
  ],
  'DNA+TCRSeq': [
    ['Tracking ID', 'Required'],
    ['DMP Sample ID', 'Required'],
    ['Investigator Patient ID (Study Subject Identifier)', 'Required'],
    ['Investigator Sample ID (Study Sample Identifier)', 'Required'],
    ['Sample Type', 'Required'],
    ['Specimen Type', 'Required'],
    ['Project PI', 'Required'],
    ['Project Title', 'Required'],
    ['DMP to Transfer', 'Required'],
    ['Molecular Pathology Accession Number', 'Optional'],
  ],
  'DNA+HumanWholeGenome ': [
    ['Tracking ID', 'Required'],
    ['DMP Sample ID', 'Required'],
    ['Investigator Patient ID (Study Subject Identifier)', 'Required'],
    ['Investigator Sample ID (Study Sample Identifier)', 'Required'],
    ['Sample Type', 'Required'],
    ['Specimen Type', 'Required'],
    ['Project PI', 'Required'],
    ['Project Title', 'Required'],
    ['DMP to Transfer', 'Required'],
    ['Molecular Pathology Accession Number', 'Optional'],
  ],
  'DNA+IMPACT468': [
    ['Tracking ID', 'Required'],
    ['DMP Sample ID', 'Required'],
    ['Investigator Patient ID (Study Subject Identifier)', 'Required'],
    ['Investigator Sample ID (Study Sample Identifier)', 'Required'],
    ['Sample Type', 'Required'],
    ['Specimen Type', 'Required'],
    ['Project PI', 'Required'],
    ['Project Title', 'Required'],
    ['DMP to Transfer', 'Required'],
    ['Molecular Pathology Accession Number', 'Optional'],
  ],
  'DNA+ddPCR': [
    ['Tracking ID', 'Required'],
    ['DMP Sample ID', 'Required'],
    ['Investigator Patient ID (Study Subject Identifier)', 'Required'],
    ['Investigator Sample ID (Study Sample Identifier)', 'Required'],
    ['Sample Type', 'Required'],
    ['Specimen Type', 'Required'],
    ['Project PI', 'Required'],
    ['Project Title', 'Required'],
    ['DMP to Transfer', 'Required'],
    'Gene and Mutation',
    ['Molecular Pathology Accession Number', 'Optional'],
  ],
  'DNA+WholeExomeSequencing ': [
    ['Tracking ID', 'Required'],
    ['DMP Sample ID', 'Required'],
    ['Investigator Patient ID (Study Subject Identifier)', 'Required'],
    ['Investigator Sample ID (Study Sample Identifier)', 'Required'],
    ['Sample Type', 'Required'],
    ['Specimen Type', 'Required'],
    ['Project PI', 'Required'],
    ['Project Title', 'Required'],
    ['DMP to Transfer', 'Required'],
    ['Sample Approved by CMO', 'Required'],
    ['Variant Allele Frequency', 'Required'],
    ['Coverage', 'Required'],
    [
      'Investigator Patient ID (Investigator Provided Study Subject Identifier)',
      'Required',
    ],
    [
      'Investigator Sample ID (Investigator Provided Study Sample Identifier)',
      'Required',
    ],
    ['Additional Info', 'Optional'],
    ['Molecular Pathology Accession Number', 'Optional'],
  ],
  'DNA Library+HumanWholeGenome ': [
    ['Tracking ID', 'Required'],
    ['DMP Sample ID', 'Required'],
    ['Investigator Patient ID (Study Subject Identifier)', 'Required'],
    ['Investigator Sample ID (Study Sample Identifier)', 'Required'],
    ['Sample Type', 'Required'],
    ['Specimen Type', 'Required'],
    ['Project PI', 'Required'],
    ['Project Title', 'Required'],
    ['DMP to Transfer', 'Required'],
    ['Molecular Pathology Accession Number', 'Optional'],
  ],
  'DNA Library+IMPACT468': [
    ['Tracking ID', 'Required'],
    ['DMP Sample ID', 'Required'],
    ['Investigator Patient ID (Study Subject Identifier)', 'Required'],
    ['Investigator Sample ID (Study Sample Identifier)', 'Required'],
    ['Sample Type', 'Required'],
    ['Specimen Type', 'Required'],
    ['Project PI', 'Required'],
    ['Project Title', 'Required'],
    ['DMP to Transfer', 'Required'],
    ['Molecular Pathology Accession Number', 'Optional'],
  ],
  'DNA Library+ddPCR': [
    ['Tracking ID', 'Required'],
    ['DMP Sample ID', 'Required'],
    ['Investigator Patient ID (Study Subject Identifier)', 'Required'],
    ['Investigator Sample ID (Study Sample Identifier)', 'Required'],
    ['Sample Type', 'Required'],
    ['Specimen Type', 'Required'],
    ['Project PI', 'Required'],
    ['Project Title', 'Required'],
    ['DMP to Transfer', 'Required'],
    ['Gene and Mutation', 'Optional'],
    [' Molecular Pathology Accession Number', 'Optional'],
  ],
  'DNA Library+WholeExomeSequencing ': [
    ['Tracking ID', 'Required'],
    ['DMP Sample ID', 'Required'],
    ['Investigator Patient ID (Study Subject Identifier)', 'Required'],
    ['Investigator Sample ID (Study Sample Identifier)', 'Required'],
    ['Sample Type', 'Required'],
    ['Specimen Type', 'Required'],
    ['Project PI', 'Required'],
    ['Project Title', 'Required'],
    ['DMP to Transfer', 'Required'],
    ['Sample Approved by CMO', 'Required'][
      ('Variant Allele Frequency', 'Required')
    ],
    ['Coverage', 'Required'],
    [
      'Investigator Patient ID (Investigator Provided Study Subject Identifier)',
      'Required',
    ],
    [
      'Investigator Sample ID (Investigator Provided Study Sample Identifier)',
      'Required',
    ],
    ['Additional Info', 'Optional'],
    ['Molecular Pathology Accession Number', 'Optional'],
  ],
  'DNA Library+CustomCapture': [
    ['Tracking ID', 'Required'],
    ['DMP Sample ID', 'Required'],
    ['Investigator Patient ID (Study Subject Identifier)', 'Required'],
    ['Investigator Sample ID (Study Sample Identifier)', 'Required'],
    ['Sample Type', 'Required'],
    ['Specimen Type', 'Required'],
    ['Project PI', 'Required'],
    ['Project Title', 'Required'],
    ['DMP to Transfer', 'Required'],
    ['Molecular Pathology Accession Number', 'Optional'],
  ],
  'DNA Library+QC_Pickup': [
    ['Tracking ID', 'Required'],
    ['DMP Sample ID', 'Required'],
    ['Investigator Patient ID (Study Subject Identifier)', 'Required'],
    ['Investigator Sample ID (Study Sample Identifier)', 'Required'],
    ['Sample Type', 'Required'],
    ['Specimen Type', 'Required'],
    ['Project PI', 'Required'],
    ['Project Title', 'Required'],
    ['DMP to Transfer', 'Required'],
    ['Molecular Pathology Accession Number', 'Optional'],
  ],
  'DNA Library+TCRSeq': [
    ['Tracking ID', 'Required'],
    ['DMP Sample ID', 'Required'],
    ['Investigator Patient ID (Study Subject Identifier)', 'Required'],
    ['Investigator Sample ID (Study Sample Identifier)', 'Required'],
    ['Sample Type', 'Required'],
    ['Specimen Type', 'Required'],
    ['Project PI', 'Required'],
    ['Project Title', 'Required'],
    ['DMP to Transfer', 'Required'],
    ['Molecular Pathology Accession Number', 'Optional'],
  ],
};
