// readable recipe names
export const readableRecipesLib = {
    "ATAC": "ATAC Sequencing",
    "User_ATAC": "ATAC Sequencing (Library)",
    "HC_ACCESS": "MSK-ACCESS",
    "HC_CMOCH": "CMO-CH",
    "HC_Custom": "Custom Capture",
    "HC_IMPACT": "IMPACT",
    "HC_IMPACT-Heme": "IMPACT-Heme",
    "HC_IMPACT-Mouse": "Mouse IMPACT",
    "ddPCR": "ddPCR",
    "DNA_Amplicon": "Amplicon Sequencing",
    "User_Amplicon": "Amplicon Sequencing (Library)",
    "DNA_ChIP": "ChIP Sequencing",
    "User_ChIP": "ChIP Sequencing (Library)",
    "DNA_CRISPR": "CRISPR Sequencing",
    "DNA_CUT&RUN": "CUT&RUN Sequencing",
    "User_CUT&RUN": "CUT&RUN Sequencing (Library)",
    "DNA_SingleCellCNV": "Single Cell CNV Sequencing",
    "User_SingleCellCNV": "Single Cell CNV Sequencing (Library)",
    "Extraction_cfDNA": "cfDNA Extraction",
    "Extraction_DNA": "DNA Extraction",
    "Extraction_Dual": "Dual DNA/RNA Extraction",
    "Extraction_RNA": "RNA Extraction",
    "Methyl_Capture": "Methylation Capture Sequencing",
    "Methyl_WGS": "Whole Genome Methylation Sequencing",
    "Nanopore_AS": "Nanopore Adaptive Sampling",
    "Nanopore_cDNA": "Nanopore cDNA Sequencing",
    "Nanopore_Chromium": "Nanopore 10X cDNA Sequencing",
    "Nanopore_Long-DNA": "Nanopore Long Read DNA Sequencing",
    "Nanopore_RNA":	"Nanopore Direct RNA Sequencing",
    "Nanopore_Short-DNA": "Nanopore Short Read DNA Sequencing",
    "PEDPEG": "PED-PEG",
    "QC_DNA": "DNA QC",
    "QC_Library": "Library QC",
    "QC_RNA": "RNA QC",
    "R&D_Other": "IGO R&D Use Only",
    "RNA_PolyA": "RNA Seq - PolyA",
    "RNA_Ribodeplete": "RNA Seq - Ribodepletion",
    "RNA_SMARTer-Cells": "SMARTer from Cells",
    "RNA_SMARTer-RNA": "RNA Seq - SMARTer",
    "SC_Chromium-ATAC":	"10X scATAC Sequencing",
    "User_Chromium-ATAC": "10X scATAC Sequencing (Library)",
    "SC_Chromium-BCR": "10X scVDJ (BCR) Sequencing",
    "SC_Chromium-FB-3": "10X 3' Feature Barcode/Hashtag Sequencing",
    "SC_Chromium-FB-5":	"10X 5' Feature Barcode/Hashtag Sequencing",
    "SC_Chromium-GEX-3": "10X 3' scRNA-Seq",
    "SC_Chromium-GEX-5": "10X 5' scRNA-Seq",
    "SC_Chromium-Multiome": "10X Multiome",
    "SC_Chromium-TCR": "10X scVDJ (TCR) Sequencing",
    "SC_DLP": "DLP+",
    "SC_SmartSeq": "SmartSeq (384-well)",
    "ST_CosMx": "CosMx",
    "ST_GeoMx": "GeoMx",
    "ST_Visium": "Visium",
    "ST_Visium-HD": "Visium HD",
    "User_Visium-HD": "Visium HD (Library)",
    "ST_Xenium": "Xenium",
    "TCR_IGO": "TCR Sequencing",
    "User_Chromium": "10X GEX, VDJ, FB/CH or Visium",
    "User_Methyl": "Methylation Sequencing",
    "User_MissionBio": "MissionBio",
    "User_RNA":	"RNA Sequencing",
    "User_shRNA": "shRNA Sequencing",
    "User_WGBS": "Whole Genome Bisulfite Sequencing",
    "User_WGS":	"Whole Genome Sequencing",
    "User_Capture": "Post-Capture Sequencing",
    "User_ERIL": "ERIL Library Submissions",
    "WES_Human": "Whole Exome Sequencing",
    "WES_Mouse": "Mouse Whole Exome Sequencing",
    "WGS_Deep":	"Whole Genome Sequencing (deep or PCR-free)",
    "WGS_Metagenomic": "Metagenomic Sequencing",
    "WGS_Shallow": "Shallow Whole Genome Sequencing",
    "GLP_WES": "CCV WES Submissions (GLP)",
    "GLP_RNA": "CCV RNA-Seq Submissions (GLP)",
    "OGM": "Optical Genome Mapping (Bionano)"
};
export const reverseReadableRecipesLib = {
    "ATAC Sequencing": "ATAC",
    "ATAC Sequencing (Library)": "User_ATAC",
    "MSK-ACCESS": "HC_ACCESS",
    "CMO-CH": "HC_CMOCH",
    "Custom Capture": "HC_Custom",
    "IMPACT": "HC_IMPACT",
    "IMPACT-Heme": "HC_IMPACT-Heme",
    "Mouse IMPACT": "HC_IMPACT-Mouse",
    "ddPCR": "ddPCR",
    "Amplicon Sequencing": "DNA_Amplicon",
    "Amplicon Sequencing (Library)": "User_Amplicon",
    "ChIP Sequencing": "DNA_ChIP",
    "ChIP Sequencing (Library)": "User_ChIP",
    "CRISPR Sequencing": "DNA_CRISPR",
    "CUT&RUN Sequencing": "DNA_CUT&RUN",
    "CUT&RUN Sequencing (Library)": "User_CUT&RUN",
    "Single Cell CNV Sequencing": "DNA_SingleCellCNV",
    "Single Cell CNV Sequencing (Library)": "User_SingleCellCNV",
    "cfDNA Extraction": "Extraction_cfDNA",
    "DNA Extraction": "Extraction_DNA",
    "Dual DNA/RNA Extraction": "Extraction_Dual",
    "RNA Extraction": "Extraction_RNA",
    "Methylation Capture Sequencing": "Methyl_Capture",
    "Whole Genome Methylation Sequencing": "Methyl_WGS",
    "Nanopore Adaptive Sampling": "Nanopore_AS",
    "Nanopore cDNA Sequencing": "Nanopore_cDNA",
    "Nanopore 10X cDNA Sequencing": "Nanopore_Chromium",
    "Nanopore Long Read DNA Sequencing": "Nanopore_Long-DNA",
    "Nanopore Direct RNA Sequencing": "Nanopore_RNA",
    "Nanopore Short Read DNA Sequencing": "Nanopore_Short-DNA",
    "PED-PEG": "PEDPEG",
    "DNA QC": "QC_DNA",
    "Library QC": "QC_Library",
    "RNA QC": "QC_RNA",
    "IGO R&D Use Only": "R&D_Other",
    "RNA Seq - PolyA": "RNA_PolyA",
    "RNA Seq - Ribodepletion": "RNA_Ribodeplete",
    "SMARTer from Cells": "RNA_SMARTer-Cells",
    "RNA Seq - SMARTer": "RNA_SMARTer-RNA",
    "10X scATAC Sequencing": "SC_Chromium-ATAC",
    "10X scATAC Sequencing (Library)": "User_Chromium-ATAC",
    "10X scVDJ (BCR) Sequencing": "SC_Chromium-BCR",
    "10X 3' Feature Barcode/Hashtag Sequencing": "SC_Chromium-FB-3",
    "10X 5' Feature Barcode/Hashtag Sequencing": "SC_Chromium-FB-5",
    "10X 3' scRNA-Seq": "SC_Chromium-GEX-3",
    "10X 5' scRNA-Seq": "SC_Chromium-GEX-5",
    "10X Multiome": "SC_Chromium-Multiome",
    "10X scVDJ (TCR) Sequencing": "SC_Chromium-TCR",
    "DLP+": "SC_DLP",
    "SmartSeq (384-well)": "SC_SmartSeq",
    "CosMx": "ST_CosMx",
    "GeoMx": "ST_GeoMx",
    "Visium": "ST_Visium",
    "Visium HD": "ST_Visium-HD",
    "Visium HD (Library)": "User_Visium-HD",
    "Xenium": "ST_Xenium",
    "TCR Sequencing": "TCR_IGO",
    "10X GEX, VDJ, FB/CH or Visium": "User_Chromium",
    "Methylation Sequencing": "User_Methyl",
    "MissionBio": "User_MissionBio",
    "RNA Sequencing": "User_RNA",
    "shRNA Sequencing": "User_shRNA",
    "Whole Genome Bisulfite Sequencing": "User_WGBS",
    "Whole Genome Sequencing": "User_WGS",
    "Post-Capture Sequencing": "User_Capture",
    "ERIL Library Submissions": "User_ERIL",
    "Whole Exome Sequencing": "WES_Human",
    "Mouse Whole Exome Sequencing": "WES_Mouse",
    "Whole Genome Sequencing (deep or PCR-free)": "WGS_Deep",
    "Metagenomic Sequencing": "WGS_Metagenomic",
    "Shallow Whole Genome Sequencing": "WGS_Shallow",
    "CCV WES Submissions (GLP)": "GLP_WES",
    "CCV RNA-Seq Submissions (GLP)": "GLP_RNA",
    "Optical Genome Mapping (Bionano)": "OGM"
};
